#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-WWW-RobotRules
Version  : 6.02
Release  : 8
URL      : http://www.cpan.org/CPAN/authors/id/G/GA/GAAS/WWW-RobotRules-6.02.tar.gz
Source0  : http://www.cpan.org/CPAN/authors/id/G/GA/GAAS/WWW-RobotRules-6.02.tar.gz
Summary  : database of robots.txt-derived permissions
Group    : Development/Tools
License  : Artistic-1.0-Perl
Requires: perl-WWW-RobotRules-doc
BuildRequires : perl(URI)

%description
NAME
WWW::RobotRules - database of robots.txt-derived permissions
SYNOPSIS
use WWW::RobotRules;
my $rules = WWW::RobotRules->new('MOMspider/1.0');

%package doc
Summary: doc components for the perl-WWW-RobotRules package.
Group: Documentation

%description doc
doc components for the perl-WWW-RobotRules package.


%prep
%setup -q -n WWW-RobotRules-6.02

%build
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make V=1  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=intel.com,localhost
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot}
else
./Build install --installdirs=site --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.22.0/WWW/RobotRules.pm
/usr/lib/perl5/site_perl/5.22.0/WWW/RobotRules/AnyDBM_File.pm

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man3/*
